In [1]:
import numpy as np
a = np.array([12,3,4,2])

In [2]:
b = np.arange(4)
print(a,b)

[12  3  4  2] [0 1 2 3]


In [3]:
print(a+b)

[12  4  6  5]


## 对np array中的的每一个数求sin值

In [10]:
print(10*np.sin(a))  

[-5.36572918  1.41120008 -7.56802495  9.09297427]


In [7]:
print(a<3)

[False False False  True]


## 求举证的内积和乘法

In [18]:
c = np.array([[1,2],
             [23,4]])
d = np.arange(4).reshape((2,2))
print(c*d)
print(np.dot(c,d))

[[ 0  2]
 [46 12]]
[[ 4  7]
 [ 8 35]]


In [19]:
e = np.random.random((2,4))

In [20]:
print(e)

[[0.09270211 0.04425251 0.55045624 0.22148112]
 [0.93686227 0.74262807 0.76561991 0.09797566]]


In [21]:
print(np.sum(e))
print(np.max(e))
print(np.min(e))

3.4519779016360523
0.9368622689981417
0.044252510818020174


In [23]:
print(np.sum(e,axis = 0))
print(np.sum(e,axis = 1))

[1.02956438 0.78688059 1.31607616 0.31945678]
[0.90889198 2.54308592]


In [24]:
A = np.arange(2,14).reshape(2,6)
print(A)

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [25]:
print(np.argmin(A))
print(np.argmax(A))

0
11


In [26]:
# 求中位数
print(np.median(A))

7.5


In [28]:
# 累加
print(np.cumsum(A))
# 累差
print(np.diff(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [29]:
print(np.nonzero(A))# 显示非零的数的位置，第一个数组是x，第二个数组是y

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))


In [30]:
print(np.sort(np.arange(14,2,-1).reshape((2,6)))) # 排序返回的是逐行排序

[[ 9 10 11 12 13 14]
 [ 3  4  5  6  7  8]]


In [32]:
print(A.T) # 矩阵的转置

[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]


In [34]:
print(np.transpose(A))

[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]


In [35]:
print(np.clip(A,3,6))

[[3 3 4 5 6 6]
 [6 6 6 6 6 6]]
