In [1]:
import numpy as np
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
print(A[2])

5


In [6]:
print(A.reshape((2,6))[1])

[ 9 10 11 12 13 14]


In [7]:
print(A.reshape((2,6))[1,1:3])

[10 11]


In [10]:
for row in A.reshape((2,6)):
    print(row)

[3 4 5 6 7 8]
[ 9 10 11 12 13 14]


In [11]:
print(A.reshape((2,6)).flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]
