In [13]:
import numpy as np 
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))
# vertical
print(A)

[[1 1 1]
 [2 2 2]]
[1 1 1]


In [2]:
print(np.hstack((A,B)))# horizental

[1 1 1 2 2 2]


In [3]:
print(A[np.newaxis,:])# 在行上面加了维度

[[1 1 1]]


In [4]:
print(A[: , np.newaxis])

[[1]
 [1]
 [1]]


In [12]:
A = A[np.newaxis,:]
B = B[np.newaxis,:]
C = np.concatenate((A,B,A),axis = 0)
print(A)
print(B)

[[[[1 1 1]]]]
[[[[2 2 2]]]]


In [11]:
print(C.shape)
print(C)

(3, 1, 3)
[[[1 1 1]]

 [[2 2 2]]

 [[1 1 1]]]


In [9]:
D = np.concatenate((A,B,A),axis = 1)
print(D.shape)

(1, 3, 3)
