In [5]:
import numpy as np
a = np.arange(4)
e = a.copy()
b = a # 相当于是同一个引用
c = a
d = b
a[0] = 11
print(a)
print(b)
print(c)
print(d)

[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]


In [2]:
b is a
c is a
d is a

True

In [6]:
e is a


False

In [7]:
print(e)

[0 1 2 3]
