In [10]:
import numpy as np 
a = np.array([1,2,3,4,5],dtype = int)
print(a)

[1 2 3 4 5]


In [11]:
print(a.shape)
b = np.array([[1,2,3],[4,5,6]])
print(b)

(5,)
[[1 2 3]
 [4 5 6]]


In [12]:
print(b.shape)

(2, 3)


In [13]:
c = np.linspace(1,10,5)
print(c)

[ 1.    3.25  5.5   7.75 10.  ]


生成5个点，4段


In [14]:
d = np.zeros((2,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
